image: python:latest

store:build:
  stage: build
  script:
  - 'curl "https://api.rebrandly.com/v1/links" -o /tmp/links.json --header "Content-Type: application/json" --header "apikey: ${RebrandlyApiKey}"'
