image: python:latest

store:build:
  stage: build
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_SSH_PRIV_KEY")
  script:
  - pip3 install requests jinja2
  - python3 ci_sources/store.py
  - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$DOMAIN "mkdir -p $DOMAIN/assets/$CI_COMMIT_REF_NAME/store"
  - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp store/* "$USERNAME@$DOMAIN:$DOMAIN/assets/$CI_COMMIT_REF_NAME/store"

