variables:
  GIT_SUBMODULE_STRATEGY: recursive

deployToStore:
  stage: deploy
  only:
    - triggers
    - web
    - api
  image: python:3.7
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SERVER_SSH_PRIV_KEY")
    - apt-get update -qq && apt-get install git -qq
    - python3 -m pip install --upgrade pip
    - pip3 install requests jinja2 gitpython
  script:
    - python3 ci_sources/store.py
    - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $USERNAME@$DOMAIN "mkdir -p www/$DOMAIN/assets/store"
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -rp store/* "$USERNAME@$DOMAIN:www/$DOMAIN/assets/store"
  allow_failure: true
