language: python
dist: xenial
python:
  - "3.7"

git:
  depth: false

jobs:
  include:
    - stage: test
      addons:
        sonarcloud:
          organization: "project-alice-assistant"
          token:
            secure: $SONAR_TOKEN
      script: sonar-scanner
    - stage: deploy
      script:
        - curl --version
        - 'curl -o "test.json" --location "https://api.rebrandly.com/v1/links" --header "Content-Type: application/json" --header "apikey: ${RebrandlyApiKey}"'
